openapi: 3.0.3
info:
  title: Micronaut
  description: Uma descrição
  version: 1.0.11
servers:
  - url: http://localhost:8080
tags:
  - name: hello
    description: hello world
paths:
  /hello-world:
    get:
      tags:
        - hello
      summary: Hello world
      description: Hello world
      operationId: helloWorld
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloWorld'
        '400':
          description: 400 error
        '404':
          description: 404 error
        '405':
          description: 405 error
components:
  schemas:
    HelloWorld:
      type: object
      properties:
        text:
          type: string
          example: hello world
